/**
 * persist.test.ts — sovereign_save_key.bin round-trip invariants.
  *
   * Pins the persistence contract from docs/roadmap/sovereign-save-key.md:
    *   "A vitest case: round-trip write → read → re-write produces
     *    byte-identical output."
      *
       * Also pins:
        *   - Version mismatch is rejected loudly (not silently).
         *   - Shape mismatch is rejected loudly.
          *   - A vacant-only tapestry round-trips (no phrases, all scale=0).
           *   - slotPhrase[] survives the round-trip byte-identically.
            *
             * The store is exercised through its public actions only — no DOM, no R3F.
              * localStorage is stubbed via a simple in-memory map so the tests run in
               * the Node/jsdom environment that Vitest uses.
                */

                import { describe, it, expect, beforeEach, vi } from "vitest";
                import {
                  useSaccadeStore,
                    MAX_NODES,
                      STRIDE,
                        TIER_CAPS,
                          TIER_STARTS,
                          } from "../store/useSaccadeStore";

                          // ── localStorage stub (Node has no real localStorage) ─────────────────
                          const _lsStore: Record<string, string> = {};
                          vi.stubGlobal("localStorage", {
                            getItem: (k: string) => _lsStore[k] ?? null,
                              setItem: (k: string, v: string) => { _lsStore[k] = v; },
                                removeItem: (k: string) => { delete _lsStore[k]; },
                                  clear: () => { for (const k in _lsStore) delete _lsStore[k]; },
                                  });

                                  // ── Helpers ────────────────────────────────────────────────────────────

                                  function resetStore() {
                                    const fresh = new Float32Array(MAX_NODES * STRIDE);
                                      const vacantSlotsByTier = TIER_CAPS.map((cap, t) => {
                                          const start = TIER_STARTS[t];
                                              const out = new Array<number>(cap);
                                                  for (let i = 0; i < cap; i++) out[i] = start + i;
                                                      return out;
                                                        });
                                                          const s = useSaccadeStore.getState();
                                                            s.mass.fill(0);
                                                              s.injectedAt.fill(0);
                                                                s.spawnTime.fill(0);
                                                                  s.reinforcementCount.fill(0);
                                                                    s.animStartTime.fill(0);
                                                                      s.embeddings.fill(0);
                                                                        useSaccadeStore.setState({
                                                                            mockFrames: [fresh],
                                                                                totalFrames: 1,
                                                                                    activeFrameIndex: 0,
                                                                                        isFileLoaded: false,
                                                                                            vacantSlotsByTier,
                                                                                                tierCounts: TIER_CAPS.map(() => 0),
                                                                                                    slotPhrase: new Array(MAX_NODES).fill(null),
                                                                                                        bvhDirty: true,
                                                                                                          });
                                                                                                            // Clear the ls stub between tests.
                                                                                                              localStorage.clear();
                                                                                                              }
                                                                                                              
                                                                                                              // Dynamically import the persist module AFTER the store mock is set up.
                                                                                                              // Using a function so each test can import fresh (avoids module-level
                                                                                                              // side-effects running before the store is reset).
                                                                                                              async function getPersist() {
                                                                                                                // Re-import to pick up any module-level side effects cleanly.
                                                                                                                  return await import("./tapestryPersist");
                                                                                                                  }
                                                                                                                  
                                                                                                                  // ── Tests ──────────────────────────────────────────────────────────────
                                                                                                                  
                                                                                                                  describe("sovereign_save_key.bin round-trip", () => {
                                                                                                                    beforeEach(resetStore);
                                                                                                                    
                                                                                                                      it("encode → decode → re-encode produces byte-identical output (vacant tapestry)", async () => {
                                                                                                                          const p = await getPersist();
                                                                                                                          
                                                                                                                              // encode round 1
                                                                                                                                  const buf1 = (p as any)._encodeTapestryForTest
                                                                                                                                        ? (p as any)._encodeTapestryForTest()
                                                                                                                                              : null;
                                                                                                                                              
                                                                                                                                                  // Use the autosave path to write to ls, then boot-load to decode.
                                                                                                                                                      p.autosaveToLocalStorage();
                                                                                                                                                          const result = p.bootLoadFromLocalStorage();
                                                                                                                                                              expect(result).not.toBeNull();
                                                                                                                                                                  expect(result!.ok).toBe(true);
                                                                                                                                                                      expect(result!.slotCount).toBe(0);
                                                                                                                                                                      
                                                                                                                                                                          // encode round 2 after loading back
                                                                                                                                                                              p.autosaveToLocalStorage();
                                                                                                                                                                                  const raw1 = localStorage.getItem("rcmt_sovereign_save_key")!;
                                                                                                                                                                                  
                                                                                                                                                                                      // Reset and reload to produce a third encode from the re-loaded state.
                                                                                                                                                                                          const result2 = p.bootLoadFromLocalStorage();
                                                                                                                                                                                              expect(result2!.ok).toBe(true);
                                                                                                                                                                                                  p.autosaveToLocalStorage();
                                                                                                                                                                                                      const raw2 = localStorage.getItem("rcmt_sovereign_save_key")!;
                                                                                                                                                                                                      
                                                                                                                                                                                                          // The base64 blobs must be identical (same frame, same empty phrases).
                                                                                                                                                                                                              // We strip the savedAt field (bytes 12-19 of the binary, offset 16-24 of
                                                                                                                                                                                                                  // base64) from both before comparing, because savedAt = Date.now() and
                                                                                                                                                                                                                      // will differ by milliseconds between the two encodes.
                                                                                                                                                                                                                          // Instead we decode and compare frame + phrase blocks only.
                                                                                                                                                                                                                              function b64ToBytes(b64: string): Uint8Array {
                                                                                                                                                                                                                                    const bin = atob(b64);
                                                                                                                                                                                                                                          const arr = new Uint8Array(bin.length);
                                                                                                                                                                                                                                                for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
                                                                                                                                                                                                                                                      return arr;
                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                              const bytes1 = b64ToBytes(raw1);
                                                                                                                                                                                                                                                                  const bytes2 = b64ToBytes(raw2);
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                      // Header bytes 0-11 (magic, version, shape) must match.
                                                                                                                                                                                                                                                                          for (let i = 0; i < 12; i++) expect(bytes1[i]).toBe(bytes2[i]);
                                                                                                                                                                                                                                                                              // Bytes 12-19 are savedAt (float64) — skip.
                                                                                                                                                                                                                                                                                  // Bytes 20 onward: phraseBlockBytes + frame + phrase block must match.
                                                                                                                                                                                                                                                                                      for (let i = 20; i < bytes1.length; i++) {
                                                                                                                                                                                                                                                                                            expect(bytes1[i]).toBe(bytes2[i]);
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                    it("encode → decode restores slotPhrase[] strings byte-identically", async () => {
                                                                                                                                                                                                                                                                                                        const p = await getPersist();
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                            // Inject a phrase via the store directly.
                                                                                                                                                                                                                                                                                                                const s = useSaccadeStore.getState();
                                                                                                                                                                                                                                                                                                                    const outcome = s.injectLiveIntentVector({
                                                                                                                                                                                                                                                                                                                          slot: 1,
                                                                                                                                                                                                                                                                                                                                textLength: 20,
                                                                                                                                                                                                                                                                                                                                      colorRGB: [0.15, 0.95, 0.89],
                                                                                                                                                                                                                                                                                                                                            phrase: "sovereign grounding substrate",
                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                    expect(outcome).not.toBeNull();
                                                                                                                                                                                                                                                                                                                                                        const slot = outcome!.index;
                                                                                                                                                                                                                                                                                                                                                            expect(s.slotPhrase[slot]).toBe("sovereign grounding substrate");
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                p.autosaveToLocalStorage();
                                                                                                                                                                                                                                                                                                                                                                    // Clear the store so we start fresh.
                                                                                                                                                                                                                                                                                                                                                                        resetStore();
                                                                                                                                                                                                                                                                                                                                                                            expect(useSaccadeStore.getState().slotPhrase[slot]).toBeNull();
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                const result = p.bootLoadFromLocalStorage();
                                                                                                                                                                                                                                                                                                                                                                                    expect(result!.ok).toBe(true);
                                                                                                                                                                                                                                                                                                                                                                                        expect(useSaccadeStore.getState().slotPhrase[slot]).toBe("sovereign grounding substrate");
                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                            it("slotCount reflects the number of occupied slots after round-trip", async () => {
                                                                                                                                                                                                                                                                                                                                                                                                const p = await getPersist();
                                                                                                                                                                                                                                                                                                                                                                                                    const s = useSaccadeStore.getState();
                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                        // Inject 3 phrases into different tiers.
                                                                                                                                                                                                                                                                                                                                                                                                            s.injectLiveIntentVector({ slot: 1, textLength: 5, colorRGB: [0.15, 0.95, 0.89], phrase: "fact one" });
                                                                                                                                                                                                                                                                                                                                                                                                                s.injectLiveIntentVector({ slot: 3, textLength: 6, colorRGB: [0.87, 0.8, 0.29],  phrase: "metric two" });
                                                                                                                                                                                                                                                                                                                                                                                                                    s.injectLiveIntentVector({ slot: 5, textLength: 5, colorRGB: [0.73, 0.46, 0.78], phrase: "dream three" });
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                        p.autosaveToLocalStorage();
                                                                                                                                                                                                                                                                                                                                                                                                                            resetStore();
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                const result = p.bootLoadFromLocalStorage();
                                                                                                                                                                                                                                                                                                                                                                                                                                    expect(result!.ok).toBe(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                        expect(result!.slotCount).toBe(3);
                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                            it("version mismatch is rejected loudly, not silently", async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                const p = await getPersist();
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                    p.autosaveToLocalStorage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const raw = localStorage.getItem("rcmt_sovereign_save_key")!;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Decode base64, mutate version bytes (offset 4-5 in binary), re-encode.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const bin = atob(raw);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const arr = new Uint8Array(bin.length);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Set version to 99 (big-endian u16 at byte offset 4).
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                arr[4] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    arr[5] = 99;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let corrupted = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (let i = 0; i < arr.length; i++) corrupted += String.fromCharCode(arr[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                localStorage.setItem("rcmt_sovereign_save_key", btoa(corrupted));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const result = p.bootLoadFromLocalStorage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        expect(result).not.toBeNull();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            expect(result!.ok).toBe(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                expect(result!.message).toMatch(/unsupported save version 99/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    it("magic mismatch is rejected loudly", async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const p = await getPersist();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            p.autosaveToLocalStorage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const raw = localStorage.getItem("rcmt_sovereign_save_key")!;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const bin = atob(raw);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const arr = new Uint8Array(bin.length);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Corrupt magic bytes 0-3.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    arr[0] = 0xde; arr[1] = 0xad; arr[2] = 0xbe; arr[3] = 0xef;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let corrupted = "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (let i = 0; i < arr.length; i++) corrupted += String.fromCharCode(arr[i]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                localStorage.setItem("rcmt_sovereign_save_key", btoa(corrupted));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const result = p.bootLoadFromLocalStorage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        expect(result!.ok).toBe(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            expect(result!.message).toMatch(/bad magic/);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                it("bootLoadFromLocalStorage returns null when no save exists", async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const p = await getPersist();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        localStorage.clear();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            expect(p.bootLoadFromLocalStorage()).toBeNull();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                it("frame buffer is byte-identical after round-trip (positions preserved)", async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const p = await getPersist();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const s = useSaccadeStore.getState();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Inject one node and record its frame buffer content.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const outcome = s.injectLiveIntentVector({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      slot: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            textLength: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  colorRGB: [0.37, 0.9, 0.2],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        phrase: "scenario node",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const slot = outcome!.index;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const frameBefore = new Float32Array(s.mockFrames[0]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        p.autosaveToLocalStorage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            resetStore();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const result = p.bootLoadFromLocalStorage();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    expect(result!.ok).toBe(true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const frameAfter = useSaccadeStore.getState().mockFrames[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Position (x, y, z) and scale must be preserved exactly.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const off = slot * STRIDE;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    expect(frameAfter[off + 0]).toBeCloseTo(frameBefore[off + 0], 5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        expect(frameAfter[off + 1]).toBeCloseTo(frameBefore[off + 1], 5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            expect(frameAfter[off + 2]).toBeCloseTo(frameBefore[off + 2], 5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                expect(frameAfter[off + 6]).toBeCloseTo(frameBefore[off + 6], 5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
